### ISSUE TITLE
Things We Are Confused About & TODO

### ISSUE THREAD

**Issue by ivan-unfolds** [besarthoxhaj/sail-back#266]
We are going to add points of confusion on here for our benefit.
- [x] Double map on email.js reducer.
- [x] What LiftN and unapply are actually doing in letters.js reducer.
- [x] Do we need a newsletter reminder letter?

**Comment by ivan-unfolds** [comment]
# Things to Do
- [x] Copy emails UI for letters.
- [x] Fix Tests.
- [x] List names of recipients.
- [x] Second letter should automatically be templated (check email).
- [x] Look into blank page on print bug.
- [x] Format the price amount on letters for amounts with only one decimal point.

**Comment by ivan-unfolds** [comment]
# Things to Do 22-06-16
- [x] Rebase commit history.
- [x] Toggle on letter UI.
- [x] Fix Tests (remove haste line from flow.config).
- [ ] Reply Rafe Linting Issue.

**Comment by ivan-unfolds** [comment]
**Inputting monetary values:**
- [x] mock data
- [x] membershiptypes database table
- [x] +subscription +donation +payment buttons on new member payment

**Rendering monetary values:**
- [x] default subscription in member view
- [x] Letters
- [x] Emails
- [x] Payment report view
- [x] payments & balance due in Member view
- [x] Member search

**Comment by jay-meister** [comment]
12/07

**Email sending**
- [x] Add subject to emails
- [x] Hook up Custom email
- [x] Concatenate email content
- [x] Check that sending the different types of emails send as expected
- [x] Filter null emails before sending them -> To be fixed on the front end, potentially by rafe
- [x] Add 'emails sent' once button has been clicked and disable button? -> look like what?
- [x] Fix potential duplicated email bug

**Letter Bugs**
- [x] Letters recipients has 'undefined' in it occassionally
- [x] Everyone is said to be owing '£0.00' -> in Rafe's hands
- [x] due date showing up as null on heroku -> make an issue
- [x] Printing Spacing
- [x] Firefox only printing 1st page

**Others**
- [x] Nulls showing up on email recipients list -> Potentially Rafe's
- [x] Bounced emails
- [x] Add more mock users to DB (including us)

**Comment by ivan-unfolds** [comment]
19/07
- [x]  add clickable members
- [x]  refactor current branch with mapping object in letters.js
- [x]  add date boundary to UI and query
- [x]  finish sub-due-letters story
- [x] style subs due component post
- [x]  add names to letter addresses

**Comment by jay-meister** [comment]
20/07

**Subs due PR**
- [x] UI for subs due for emails
- [x] send newsletter reminders tab not working
- [x] hide 'Send subscription due' button after sending
- [x] Refactor private controller
- [x] style subs due component email
- [x] fix sub due email showing £0.00
- [x] remove itallics on post component
- [x] add margin-bottom post component buttons
- [ ] Act on response from rafe: validation to date on email and post
- [ ] Act on response from rafe: payment db contains many nulls after submitting a subscription due query

**Other**
- [x] fix letter styling
- [x] ask Rafe about Richard's over flowing letter 
- [x] set up new mailgun
- [ ] style letter labels
- [x] fix new mailgun api

**Comment by jay-meister** [comment]
21/07

**subs due PR**
- [x] Act on response from rafe: validation to date on email and post
- [x]  Act on response from rafe: payment db contains many nulls after submitting a subscription due query
- [x] in redux/letters.js ensure hapi responds with payload.results 
- [x] Refactor post request in letters reducer.
- [x] Respond to empty response in subs due component

**other**
- [x]  style letter labels
- [x]  fix new mailgun api
- [x] implement new mailgun module
- [x] Clarify compose custom email UI.
