### ISSUE TITLE
Phaze 2 todo

### ISSUE THREAD

**Issue by jay-meister** [besarthoxhaj/sail-back#299]

**Comment by ivan-unfolds** [comment]
27/07
- [x] general set up of members view -- 0pts
- [x] set up hamburger menu  --  0pts
- [x] set up "My Details" navigation bar  --  0pts

**Comment by jay-meister** [comment]
- [x] finish redux
- [x] set up "My Details" navigation bar  --  0pts
- [x] add my details page 
- [x] remove react router redux
- [x] set up redux form

**Comment by jay-meister** [comment]
**Todo for contact_details**
- [x] make post api call with new data
- [x] choose fields to show
- [x] format initial values fields (stringify id)
- [x] unformat values before sending (parse id)
- [x] cancel redux form resets it
- [x] update form values after change (reply with user data from response)
- [ ] ask rafe about changing membership type
- [ ] do same as above for other My details tabs

**Separate**
- [ ] beautify fieldnames
- [ ] fix multiple field.js
- [ ] style forms
- [ ] refactor put_body
- [x] Make certain fields dropdowns, ie news_type, membership_type.

**Comment by ivan-unfolds** [comment]
04/08
- [x] Make edit buttons.
- [x] Make api call to update user
- [x] Update initial state
- [x] Link up submit button with api call
- [x] filter unwanted fields from admins fields file.
- [ ] Add information to certain fields. (From word document).
- [x] Format date.
- [ ] Style.
- [x] Fix membership_type
- [x] Move files into shared

**Comment by jay-meister** [comment]
- [ ]  Add information to certain fields. (From word document).
- [ ] Account Details tab
- [ ]  Style.

**Comment by jay-meister** [comment]
08/08
- [x] .normalize('user') as opposed to 'member' in user form reducer ??
- [x] Some error on branch add-field-description to do with redux form
- [x] Can our non redux-form components access the state of the form? I tried to connect to 'form' and none of the fields were populated..

**Comment by ivan-unfolds** [comment]
08/08
- [x] Put relevant payment files in shared. (Payments module, tables folder etc).
- [x] Populate payments table when navigating to it via menu.

**Comment by jay-meister** [comment]
09/08
- [x] fix merge bug where end membership is clicked it should show end reasons text area etc
- [x]  add actions to confirm/cancel membership.
- [x] Deletion date currently 'null'
- [x] Fix activation_status inital_value hack in memb
- [x] tests are breaking due to the initial_value in the deactivated and reactivated parts of the member.js reducer. Initial value is supposed to store the value for that field currently on the database.
- [x] deactivate_member and reactivate_member actions seem to be calling twice, not too sure why.
- [x]  Add `notes` textarea to redux form reducer and front end. 
- [x]  check user flow of end membership from Richards word doc
- [x]  Add dropdown to redux form reducer - Unsure of if i should display all options, awaiting Richards response of pivotal
- [x] hide admins notes from user
- [x] but show users old notes ???
- [x] Refactor end_membership.js
- [ ]  disable edit buttons if member is deactivated?

**Comment by jay-meister** [comment]
- [x] change letter and email queries to exclude deactivated members

**2.2 Viewable**
- [x] display standing order (conditionally)
- [x] display statements (awaiting Richard's instructions)

**2.4 Editable**
- [x] check specification for my details
- [x] Display Edit Personal Details button
- [x] Can change title, initials, first name, last name, address, primary email, secondary email, home phone, work phone, mobile phone, membership type
- [x] Member cannot change their Membership Number or their Due Date. Nor can they change any non- displayed field (as list 2.2(iii) above
- [x] Member cannot change any item in their account (ie cannot change Charges and Payments)
- [ ] If primary email address changed must check for possible duplicate,. If duplicate then disallow change and display warning message “Another member already has this email address, two members cannot carry same primary email address”)
- [ ] Membership type changed ->update date membership type changed and change subs record (if outstanding) to new membership rate.
- [ ] If member changes membership type to life single or life double set life membership date to todays date
- [x] hide option to change news type if set to 'online' (Also story 2.8)

**Comment by jay-meister** [comment]
- [x] respond to change password
- [x] clear password fields when updated
- [x] make menu disappear 
- [ ] style end membership button
- [ ] end membership, remove unwanted buttons
- [ ] change membership type
- [x] display newstype conditionally
