### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ivan-unfolds** [besarthoxhaj/sail-back#391]
- [ ] Add balance overdue to initial payment screen.
- [x] Fire off two actions || Give `payment_amount` a payload => For Displaying Credit Card Component.
- [x] Appropriate response. (`credit_card_payment` component)
- [x] Add `credit card` payment type to live DB.
- [x] disable paypal button until has been initialised
- [x] Check the logged error in paypal flow.. `Cannot read property then of undefined`

**Comment by jay-meister** [comment]
@ivanmauricio I have started with the response, and second point. I didn't move the initial request into redux as it is 2 requests so a bit more time consuming than i first thought..
Im not sure we need to do the second point anymore.

**Comment by ivan-unfolds** [comment]
- [ ] Get paypal sorted out for production.
- [x] Get ENV sorted out for production.
- [x] Error message 'Do not honor' => Sort it out.
- [x] Prettify cvv... fields
- [x] Sort out placeholders
- [x] Decide on AVS
- [x] Handle all errors
- [x] Signify to user when fields are loading
- [x] Only accept https in production
- [ ] Set up proper mailgun account
